### ISSUE TITLE
I don't think this is working the way I expected it to

### ISSUE THREAD

**Issue by SweetDeeReynolds** [grefel/indesign-endnotes#2]
Hi,
I run the script, and it turns each of my paragraphs into a numbered list. I don't want this. I thought the idea of the script was to grab the footnotes from the bottom of each page and convert them into endnotes. Am I doing something wrong?

**Comment by grefel** [comment]
This is probably a misconfiguration. To give you further advise a screenshot of your configuration panel and an IDML Example-File would be helfpful.
